name: run lint script
run-name: check lint
on: [push]

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "9.2.0"
      - run: npm install 
      - run: npm run lint
